# Generated by Django 5.0.1 on 2024-11-27 02:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_devicedatatype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedatatype',
            name='device',
        ),
        migrations.RemoveField(
            model_name='devicedatatype',
            name='id',
        ),
        migrations.AddField(
            model_name='devicedatatype',
            name='deviceDataType_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='devicedatatype',
            name='device_value_meaning',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicedatatype',
            name='supported_devices',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
