# Generated by Django 5.0.1 on 2024-11-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_remove_devicedatatype_device_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedatatype',
            old_name='deviceDataType_id',
            new_name='device_dataType_id',
        ),
    ]
