# Generated by Django 5.0.1 on 2024-11-10 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_datatable',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imei_no', models.CharField(blank=True, max_length=50, null=True)),
                ('gps_longitude', models.BigIntegerField(blank=True, null=True)),
                ('gps_latitude', models.BigIntegerField(blank=True, null=True)),
                ('gps_altitude', models.IntegerField(blank=True, null=True)),
                ('gps_angle', models.IntegerField(blank=True, null=True)),
                ('gps_satellites', models.IntegerField(blank=True, null=True)),
                ('gps_kmh', models.IntegerField(blank=True, null=True)),
                ('added_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
