# Generated by Django 5.0.1 on 2025-08-28 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franchise_partner_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSensorDataRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imei_no', models.CharField(blank=True, max_length=20, null=True)),
                ('data_type_code', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('timestring', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device_datatable',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('imei_no', models.CharField(blank=True, max_length=50, null=True)),
                ('gps_longitude', models.FloatField(blank=True, null=True)),
                ('gps_latitude', models.FloatField(blank=True, null=True)),
                ('gps_altitude', models.FloatField(blank=True, null=True)),
                ('gps_angle', models.FloatField(blank=True, null=True)),
                ('gps_satellites', models.FloatField(blank=True, null=True)),
                ('gps_kmh', models.FloatField(blank=True, null=True)),
                ('timestring', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Geofences',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('shape', models.CharField(choices=[('circle', 'Circle'), ('polygon', 'Polygon')], max_length=50)),
                ('coordinates', models.JSONField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ManyToManyField(blank=True, related_name='geofence_assigned_vehicles', to='franchise_partner_master.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('maintenance_type', models.CharField(choices=[('Fuel', 'Fuel Maintenance'), ('Tyre ', 'Tyre  Maintenance'), ('Oil', 'Oil Maintenance'), ('Maintenance', 'Maintenance')], default='Fuel', max_length=20)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('kilometer', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_related_vehicle', to='franchise_partner_master.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportExportCustomization',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('report_name', models.CharField(max_length=255)),
                ('columns', models.JSONField()),
                ('filters', models.JSONField(blank=True, null=True)),
                ('sort_order', models.JSONField(blank=True, null=True)),
                ('isRequired', models.BooleanField(default=False)),
                ('isAutoEmail', models.BooleanField(default=False)),
                ('export_duration', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportTable',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('driver', models.CharField(blank=True, max_length=50, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sensor_values', models.JSONField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('imei_no', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceScheduler',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('task', models.TextField(blank=True, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('kilometer_last', models.CharField(blank=True, default='', max_length=255)),
                ('kilometer_reminder', models.CharField(blank=True, default='', max_length=255)),
                ('notification_type', models.JSONField(default=list)),
                ('time_reminder', models.IntegerField(blank=True, default='')),
                ('time_service', models.DateField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_assigned_vehicles', to='franchise_partner_master.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('trip_name', models.CharField(blank=True, max_length=255)),
                ('start_location_latitude', models.FloatField()),
                ('start_location_longitude', models.FloatField()),
                ('start_location_address', models.TextField()),
                ('end_location_latitude', models.FloatField()),
                ('end_location_longitude', models.FloatField()),
                ('end_location_address', models.TextField()),
                ('waypoints', models.JSONField()),
                ('distance', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('trip_status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('estimated_start_time', models.DateTimeField()),
                ('estimated_end_time', models.DateTimeField()),
                ('geofence_enabled', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='franchise_partner_master.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
