# Generated by Django 5.0.1 on 2024-11-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_datatable',
            name='added_time',
        ),
    ]
