# Generated by Django 5.0.1 on 2025-08-28 09:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesensordatarecord',
            name='batch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicesensordatarecord',
            name='element_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicesensordatarecord',
            name='guid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='devicesensordatarecord',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
