# Generated by Django 5.0.1 on 2024-11-10 13:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_transaction', '0002_remove_device_datatable_added_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_datatable',
            name='device_record_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
