# Generated by Django 5.0.1 on 2024-11-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_transaction', '0003_alter_device_datatable_device_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_datatable',
            name='gps_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device_datatable',
            name='gps_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device_datatable',
            name='gps_kmh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device_datatable',
            name='gps_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device_datatable',
            name='gps_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device_datatable',
            name='gps_satellites',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
