# Generated by Django 5.0.1 on 2024-11-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_transaction', '0004_alter_device_datatable_gps_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_datatable',
            name='timestring',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
