# Generated by Django 5.0.1 on 2024-11-30 03:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_transaction', '0005_device_datatable_timestring'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSensorDataRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('imei_no', models.CharField(blank=True, max_length=20, null=True)),
                ('data_type_code', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('timestring', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
