# Generated by Django 5.0.1 on 2024-12-16 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_transaction', '0006_devicesensordatarecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTable',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_id', models.CharField(blank=True, null=True)),
                ('sensor_values', models.JSONField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, null=True)),
                ('imei_no', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
