# Generated by Django 5.0.1 on 2024-12-30 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_master', '0008_alter_accountdevice_vehicle'),
        ('franchise_partner_transaction', '0007_reporttable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('maintenance_type', models.CharField(choices=[('Fuel', 'Fuel Maintenance'), ('Tyre ', 'Tyre  Maintenance'), ('Oil', 'Oil Maintenance'), ('Maintenance', 'Maintenance')], default='Fuel', max_length=20)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('kilometer', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_related_vehicle', to='franchise_partner_master.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
