# Generated by Django 5.0.1 on 2025-01-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_transaction', '0009_reportexportcustomization'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportexportcustomization',
            name='isRequired',
            field=models.BooleanField(default=False),
        ),
    ]
