# Generated by Django 5.0.1 on 2025-01-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_transaction', '0010_reportexportcustomization_isrequired'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportexportcustomization',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportexportcustomization',
            name='export_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportexportcustomization',
            name='isAutoEmail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportexportcustomization',
            name='filters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
