# Generated by Django 5.0.1 on 2025-01-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_transaction', '0011_reportexportcustomization_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttable',
            name='driver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
