# Generated by Django 5.0.1 on 2025-01-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_transaction', '0012_reporttable_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicesensordatarecord',
            name='record_id',
        ),
        migrations.AddField(
            model_name='devicesensordatarecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=True),
            preserve_default=False,
        ),
    ]
