# Generated by Django 5.0.1 on 2025-01-08 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_master', '0009_vehicle_maintenance_period'),
        ('franchise_partner_transaction', '0013_remove_devicesensordatarecord_record_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesensordatarecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ServiceScheduler',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('task', models.TextField(blank=True, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('kilometer_last', models.CharField(blank=True, default='', max_length=255)),
                ('kilometer_reminder', models.CharField(blank=True, default='', max_length=255)),
                ('notification_type', models.JSONField(default=list)),
                ('time_reminder', models.IntegerField(blank=True, default='')),
                ('time_service', models.DateField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_assigned_vehicles', to='franchise_partner_master.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
