# Generated by Django 5.0.1 on 2025-01-09 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_master', '0009_vehicle_maintenance_period'),
        ('franchise_partner_transaction', '0014_alter_devicesensordatarecord_id_servicescheduler'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofences',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('shape', models.CharField(choices=[('circle', 'Circle'), ('polygon', 'Polygon')], max_length=50)),
                ('coordinates', models.JSONField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ManyToManyField(blank=True, related_name='geofence_assigned_vehicles', to='franchise_partner_master.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
