# Generated by Django 5.0.1 on 2024-10-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
