# Generated by Django 5.0.1 on 2024-11-10 12:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_master', '0002_order_cancel_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdevice',
            name='id',
        ),
        migrations.AddField(
            model_name='accountdevice',
            name='account_device_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
