# Generated by Django 5.0.1 on 2024-11-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_master', '0003_remove_accountdevice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdevice',
            name='date_added',
        ),
    ]
