# Generated by Django 5.0.1 on 2024-11-19 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_master', '0004_remove_accountdevice_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdevice',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_devices', to='franchise_partner_master.vehicle'),
        ),
    ]
