# Generated by Django 5.0.1 on 2024-11-19 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_master', '0005_accountdevice_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdevice',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Account_devices', to='franchise_partner_master.vehicle'),
        ),
    ]
