# Generated by Django 5.0.1 on 2025-01-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_master', '0008_alter_accountdevice_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='maintenance_period',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
