# Generated by Django 5.0.1 on 2025-01-22 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_partner_master', '0009_vehicle_maintenance_period'),
        ('master', '0004_rename_devicedatatype_id_devicedatatype_device_datatype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle_type', to='master.vehicletype'),
        ),
    ]
